spring:
    datasource:
      url: jdbc:mysql://localhost:3306/identity-service
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    jwt:
      signerKey: "xN1doWzVT8+yvHwfqe7NXP7tSd023IKRlsc/2H606c8zdTR/dgVzDrLLpX/pMnwz"
      valid-duration: 60 # in second
      refreshable-duration: 120 # in second


